version: '3.8'
services:
  # nginx
  nginx:
    build: ./nginx
    depends_on:
      - website
      - back-end
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - mynetwork

  # website
  website:
    build: ./website
    ports:
      - 3000:3000
    volumes:
      - ./website/:/src
      - /node_modules
    env_file:
      - .env
    networks:
      - mynetwork

  # back-end
  back-end:
    build: ./back-end
    depends_on:
      - mongo
    ports:
      - 8000:8000
    command: python main.py
    volumes:
      - ./back-end/:/app
  
    env_file:
      - .env
    networks:
      - mynetwork

  # mongodb
  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./:/app/data/db
    networks:
      - mynetwork

  # backup
  backup:
    build: ./backup
    depends_on:
      - mongo
    ports:
      - 8001:8001
    env_file:
      - .env
    command: python3 main.py
    volumes:
      - ./backup/:/app
    networks:
      - mynetwork

networks:
  mynetwork: